name: Mirror EDC-CE Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name "ronaks9065"
        git config --global user.email "ronak.prajapati@caxsol.com"
    
    - name: Clone Repository
      run: |
        git clone --mirror https://github.com/sovity/edc-ce.git

    - name: Get latest tag
      id: latest_tag
      run: |
        cd edc-ce.git
        latest_tag=$(git tag --sort=version:refname | tail -n 1)
        echo "Latest tag: $latest_tag"
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Fetch the specific latest tag from upstream
      run: |
        cd edc-ce.git
        ls
        git fetch origin tag "$latest_tag"
    
    - name: Push to destination repository
      env:
        DEST_REPO: https://$GITHUB_ACTOR:${{ secrets.DESTINATION_REPO_TOKEN }}@github.com/ronaks9065/mirror-edc-ce-repo.git
        BRANCH: main
      run: |
        cd edc-ce.git
        git push "$DEST_REPO" "$BRANCH" "refs/tags/$latest_tag"
